kind: Service
apiVersion: v1

metadata:
  name: udagram-frontend
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: udagram-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
