apiVersion: v1
kind: Service

metadata:
  name: reverseproxy-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - name: http
      protocol: TCP
      port: 8080

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: reverseproxy
#   name: reverseproxy-svc
# spec:
#   ports:
#   - name: "8080"
#     port: 8080
#     targetPort: 8080
#   selector:
#     service: reverseproxy 