apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-app
  labels:
    app: feeds-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feeds-app
  template:
    metadata:
      labels:
        app: feeds-app
    spec:
      containers:
      - name: restapi-feeds
        image: emanana/restapi-feeds
        ports:
        - containerPort: 80
        env:
        - name: POSTGRESS_USERNAME
          value: "emanana"
        - name: POSTGRESS_PASSWORD
          value: "Siyamthanda2017"
        - name: POSTGRESS_DB
          value: "udagrammananadev"
        - name: POSTGRESS_HOST
          value: "udagrammananadev.clyswua31odz.us-east-1.rds.amazonaws.com"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_BUCKET
          value: "udagram-manana-dev"
        - name: JWT_SECRET
          value: "hello world"

          # test